---
version: "2"

run:
  timeout: 1m30s

issues:
  fix: true

output:
  sort-order:
    - file
    - linter

linters:
  default: fast

  enable:
    - wsl_v5

  disable:
    - wsl

  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/gocolly/colly
            - github.com/stretchr/testify

    gocognit:
      min-complexity: 18

    gocyclo:
      min-complexity: 18

    godoclint:
      options:
        max-len:
          length: 120

    godot:
      capital: true

    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - golines

  settings:
    gofumpt:
      extra-rules: true

    golines:
      tab-len: 4
      max-len: 120
