name: Lint Renovate
run-name: Lint Renovate configuration file
description: Lints Renovate configuration file when a pull request is opened, reopened or synchronized.
permissions: {}

on:
  pull_request:
    paths:
      - .github/renovate.json

jobs:
  lint-renovate:
    name: Lint Renovate configuration file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Renovate configuration file
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          sparse-checkout: .github/renovate.json
          persist-credentials: false
          sparse-checkout-cone-mode: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24 # Equivalent to the latest version of Node.js v24.x.x.

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.8

      - name: Install Renovate
        run: |
          bun install --global renovate@latest
          echo 'export PATH="/root/.bun/bin:$PATH"' >> ~/.bashrc

      - name: Lint Renovate configuration file
        run: renovate-config-validator .github/renovate.json

concurrency:
  group: lint-renovate_${{ github.event.pull_request.number }}
  cancel-in-progress: true
