name: Lint Dependabot and GitHub Actions
run-name: Lint Dependabot configuration file and GitHub Actions workflows
description: Lints Dependabot configuration file and GitHub Actions workflows when code is pushed to the main branch or a pull request is opened, reopened or synchronized.
permissions: {}

on:
  push:
    paths:
      - .github/workflows/**/*
      - .github/dependabot.yml
      - zizmor.yml
    branches:
      - main

  schedule: # To find new issues when Zizmor version is updated by Renovate
    - cron: 0 8 1 * *

  pull_request:
    paths:
      - .github/workflows/**/*
      - .github/dependabot.yml
      - zizmor.yml

jobs:
  lint-dependabot-and-workflows:
    name: Lint Dependabot configuration file and GitHub Actions workflows
    runs-on: ubuntu-latest

    permissions:
      security-events: write # To create security alerts

    steps:
      - name: Checkout Dependabot configuration file, GitHub Actions workflows directory, and Zizmor configuration file
        uses: actions/checkout@v6
        with:
          ref: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.ref) || '' }}
          sparse-checkout: |
            .github/workflows
            .github/dependabot.yml
            zizmor.yml
          persist-credentials: false
          sparse-checkout-cone-mode: false

      - name: Lint Dependabot configuration file and GitHub Actions workflows
        uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0
        with:
          persona: auditor
          version: v1.22.0
          advanced-security: ${{ env.ACT != 'true' }}

concurrency:
  group: lint-github-workflows_${{ github.event.pull_request.number }}
  cancel-in-progress: true
